In [129]:
import numpy as np
import pandas as pd
from collections import Counter

In [9]:
df = pd.read_csv("Social_Network_ads.csv")

In [12]:
df = df.iloc[:, 1:]

In [13]:
df

     Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [16]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['Gender'] = encoder.fit_transform(df["Gender"])
df

     Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]

In [31]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()


X = df.iloc[:, 0 : 3].values
y = df.iloc[:, -1].values
X = scaler.fit_transform(X)
X

array([[ 1.02020406, -1.78179743, -1.49004624],
       [ 1.02020406, -0.25358736, -1.46068138],
       [-0.98019606, -1.11320552, -0.78528968],
       ...,
       [-0.98019606,  1.17910958, -1.46068138],
       [ 1.02020406, -0.15807423, -1.07893824],
       [-0.98019606,  1.08359645, -0.99084367]], shape=(400, 3))

In [32]:
type(X)

numpy.ndarray

In [182]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 10 )

In [183]:
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.925

In [184]:
df

     Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]

In [185]:
class knn:
    def __init__(self, k = 5):
        self.n_neighbors = k
        self.X_train = None
        self.y_train = None

    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train

    def predict(self, X_test):
        y_pred= []
        
        for i in X_test:
            # calculate distance with each training point
            distances = []
            for j in self.X_train:
                distances.append(self.calculate_distance(i, j))
                
            # print(sorted(list(enumerate(distances)), key = lambda x : x[1])[0: self.n_neighbors])
            distances = enumerate(distances)
            distances = list(distances) # it gives the index number, based on current situation(now it correspondence to trainin data in sequence)
            distances = sorted(distances, key = lambda x : x[1])[0 : self.n_neighbors]
            n_neighbors = distances

            label = self.majority_count(n_neighbors)
            y_pred.append(label)
        return np.array(y_pred)

    def calculate_distance(self, point_A, point_B):
        
        return np.linalg.norm(point_A - point_B)

    def majority_count(self, neighbors):
        votes = []
        for i in neighbors:
            votes.append(self.y_train[i[0]])

        votes = Counter(votes)
        return votes.most_common()[0][0]

In [186]:
a = knn(k = 5)
a.fit(X_train,y_train)

In [187]:
y_pred1= a.predict(X_test)

In [188]:
y_pred1

array([0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1])

In [189]:
print(accuracy_score(y_test, y_pred1))

0.925